### ISSUE TITLE
prototype with various WASM engines

### ISSUE THREAD

**Issue by raulk** [filecoin-project/fvm-specs#14]
* wasmer
* wasmtime 
* wasm3 (interpreter)

**Comment by Stebalien** [comment]
> wasmtime

This is going to be tricky because it doesn't support per-instruction gas values. Instead, every instruction just costs one "gas". In practice, that may actually be reasonable, but we'll have to see what the costs turn out to be.

**Comment by raulk** [comment]
We chose to build on wasmtime because it's backed by the Bytecode Alliance, which gives us better assurances about its fate, roadmap, and continuity. We eventually may introduce an abstraction layer, but it's unclear what the eventual motivators would be.

**Comment by Stebalien** [comment]
Also note:

- We went with instrumentation for gas tracing, so we don't depend on any particular WASM VM for that.
- Unfortunately, we can't really rely on wasmer's optimizations as we need to assume the pessimistic worst-case.
