### ISSUE TITLE
decide on high-level SDK sugars for method dispatch

### ISSUE THREAD

**Issue by raulk** [filecoin-project/fvm-specs#28]
Discussion originally starts here: https://github.com/filecoin-project/fvm-project/pull/4#discussion_r723738709

**Comment by raulk** [comment]
Being worked on in https://github.com/filecoin-project/devgrants/issues/562.

**Comment by anorth** [comment]
Also https://github.com/helix-onchain/filecoin (for the calling convention presented in https://github.com/filecoin-project/FIPs/discussions/382)
