### ISSUE TITLE
Use negative numbers for system exit codes

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/fvm-specs#55]
Currently, system exit codes are the codes 0-15.

It would be slightly cleaner to define the exit code as an i32, where:

1. 0 -> ok.
2. (-∞,0) -> system
3. (0,∞) -> actor

However, this might also fall into the category of "unnecessary breakage".

**Comment by raulk** [comment]
We instead went with namespacing in the uint space: https://github.com/filecoin-project/fvm-specs/blob/main/07-errors.md
