### ISSUE TITLE
Specify FVM syscalls

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/fvm-specs#61]
Create a `syscalls.md` document that specifies:

1. The syscall calling convention.
2. What syscalls are available.
3. Syscall arguments.

Then merge in the syscall error documentation from https://github.com/filecoin-project/fvm-specs/blob/main/07-errors.md.

**Comment by raulk** [comment]
The source of truth for syscalls is the Rust docs for the low-level native SDK: https://docs.rs/fvm_sdk/latest/fvm_sdk/actor/index.html
